apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/perf-prefix-000000.yaml
- manifests/perf-prefix-000001.yaml
- manifests/perf-prefix-000002.yaml
- manifests/perf-prefix-000003.yaml
- manifests/perf-prefix-000004.yaml
- manifests/perf-prefix-000005.yaml
- manifests/perf-prefix-000006.yaml
- manifests/perf-prefix-000007.yaml
- manifests/perf-prefix-000008.yaml
- manifests/perf-prefix-000009.yaml
- manifests/perf-prefix-000010.yaml
- manifests/perf-prefix-000011.yaml
- manifests/perf-prefix-000012.yaml
- manifests/perf-prefix-000013.yaml
- manifests/perf-prefix-000014.yaml
- manifests/perf-prefix-000015.yaml
- manifests/perf-prefix-000016.yaml
- manifests/perf-prefix-000017.yaml
- manifests/perf-prefix-000018.yaml
- manifests/perf-prefix-000019.yaml
- manifests/perf-prefix-000020.yaml
- manifests/perf-prefix-000021.yaml
- manifests/perf-prefix-000022.yaml
- manifests/perf-prefix-000023.yaml
- manifests/perf-prefix-000024.yaml
- manifests/perf-prefix-000025.yaml
- manifests/perf-prefix-000026.yaml
- manifests/perf-prefix-000027.yaml
- manifests/perf-prefix-000028.yaml
- manifests/perf-prefix-000029.yaml
- manifests/perf-prefix-000030.yaml
- manifests/perf-prefix-000031.yaml
- manifests/perf-prefix-000032.yaml
- manifests/perf-prefix-000033.yaml
- manifests/perf-prefix-000034.yaml
- manifests/perf-prefix-000035.yaml
- manifests/perf-prefix-000036.yaml
- manifests/perf-prefix-000037.yaml
- manifests/perf-prefix-000038.yaml
- manifests/perf-prefix-000039.yaml
- manifests/perf-prefix-000040.yaml
- manifests/perf-prefix-000041.yaml
- manifests/perf-prefix-000042.yaml
- manifests/perf-prefix-000043.yaml
- manifests/perf-prefix-000044.yaml
- manifests/perf-prefix-000045.yaml
- manifests/perf-prefix-000046.yaml
- manifests/perf-prefix-000047.yaml
- manifests/perf-prefix-000048.yaml
- manifests/perf-prefix-000049.yaml
- manifests/perf-prefix-000050.yaml
- manifests/perf-prefix-000051.yaml
- manifests/perf-prefix-000052.yaml
- manifests/perf-prefix-000053.yaml
- manifests/perf-prefix-000054.yaml
- manifests/perf-prefix-000055.yaml
- manifests/perf-prefix-000056.yaml
- manifests/perf-prefix-000057.yaml
- manifests/perf-prefix-000058.yaml
- manifests/perf-prefix-000059.yaml
- manifests/perf-prefix-000060.yaml
- manifests/perf-prefix-000061.yaml
- manifests/perf-prefix-000062.yaml
- manifests/perf-prefix-000063.yaml
- manifests/perf-prefix-000064.yaml
- manifests/perf-prefix-000065.yaml
- manifests/perf-prefix-000066.yaml
- manifests/perf-prefix-000067.yaml
- manifests/perf-prefix-000068.yaml
- manifests/perf-prefix-000069.yaml
- manifests/perf-prefix-000070.yaml
- manifests/perf-prefix-000071.yaml
- manifests/perf-prefix-000072.yaml
- manifests/perf-prefix-000073.yaml
- manifests/perf-prefix-000074.yaml
- manifests/perf-prefix-000075.yaml
- manifests/perf-prefix-000076.yaml
- manifests/perf-prefix-000077.yaml
- manifests/perf-prefix-000078.yaml
- manifests/perf-prefix-000079.yaml
- manifests/perf-prefix-000080.yaml
- manifests/perf-prefix-000081.yaml
- manifests/perf-prefix-000082.yaml
- manifests/perf-prefix-000083.yaml
- manifests/perf-prefix-000084.yaml
- manifests/perf-prefix-000085.yaml
- manifests/perf-prefix-000086.yaml
- manifests/perf-prefix-000087.yaml
- manifests/perf-prefix-000088.yaml
- manifests/perf-prefix-000089.yaml
- manifests/perf-prefix-000090.yaml
- manifests/perf-prefix-000091.yaml
- manifests/perf-prefix-000092.yaml
- manifests/perf-prefix-000093.yaml
- manifests/perf-prefix-000094.yaml
- manifests/perf-prefix-000095.yaml
- manifests/perf-prefix-000096.yaml
- manifests/perf-prefix-000097.yaml
- manifests/perf-prefix-000098.yaml
- manifests/perf-prefix-000099.yaml
- manifests/perf-prefix-000100.yaml
- manifests/perf-prefix-000101.yaml
- manifests/perf-prefix-000102.yaml
- manifests/perf-prefix-000103.yaml
- manifests/perf-prefix-000104.yaml
- manifests/perf-prefix-000105.yaml
- manifests/perf-prefix-000106.yaml
- manifests/perf-prefix-000107.yaml
- manifests/perf-prefix-000108.yaml
- manifests/perf-prefix-000109.yaml
- manifests/perf-prefix-000110.yaml
- manifests/perf-prefix-000111.yaml
- manifests/perf-prefix-000112.yaml
- manifests/perf-prefix-000113.yaml
- manifests/perf-prefix-000114.yaml
- manifests/perf-prefix-000115.yaml
- manifests/perf-prefix-000116.yaml
- manifests/perf-prefix-000117.yaml
- manifests/perf-prefix-000118.yaml
- manifests/perf-prefix-000119.yaml
- manifests/perf-prefix-000120.yaml
- manifests/perf-prefix-000121.yaml
- manifests/perf-prefix-000122.yaml
- manifests/perf-prefix-000123.yaml
- manifests/perf-prefix-000124.yaml
- manifests/perf-prefix-000125.yaml
- manifests/perf-prefix-000126.yaml
- manifests/perf-prefix-000127.yaml
- manifests/perf-prefix-000128.yaml
- manifests/perf-prefix-000129.yaml
- manifests/perf-prefix-000130.yaml
- manifests/perf-prefix-000131.yaml
- manifests/perf-prefix-000132.yaml
- manifests/perf-prefix-000133.yaml
- manifests/perf-prefix-000134.yaml
- manifests/perf-prefix-000135.yaml
- manifests/perf-prefix-000136.yaml
- manifests/perf-prefix-000137.yaml
- manifests/perf-prefix-000138.yaml
- manifests/perf-prefix-000139.yaml
- manifests/perf-prefix-000140.yaml
- manifests/perf-prefix-000141.yaml
- manifests/perf-prefix-000142.yaml
- manifests/perf-prefix-000143.yaml
- manifests/perf-prefix-000144.yaml
- manifests/perf-prefix-000145.yaml
- manifests/perf-prefix-000146.yaml
- manifests/perf-prefix-000147.yaml
- manifests/perf-prefix-000148.yaml
- manifests/perf-prefix-000149.yaml
- manifests/perf-prefix-000150.yaml
- manifests/perf-prefix-000151.yaml
- manifests/perf-prefix-000152.yaml
- manifests/perf-prefix-000153.yaml
- manifests/perf-prefix-000154.yaml
- manifests/perf-prefix-000155.yaml
- manifests/perf-prefix-000156.yaml
- manifests/perf-prefix-000157.yaml
- manifests/perf-prefix-000158.yaml
- manifests/perf-prefix-000159.yaml
- manifests/perf-prefix-000160.yaml
- manifests/perf-prefix-000161.yaml
- manifests/perf-prefix-000162.yaml
- manifests/perf-prefix-000163.yaml
- manifests/perf-prefix-000164.yaml
- manifests/perf-prefix-000165.yaml
- manifests/perf-prefix-000166.yaml
- manifests/perf-prefix-000167.yaml
- manifests/perf-prefix-000168.yaml
- manifests/perf-prefix-000169.yaml
- manifests/perf-prefix-000170.yaml
- manifests/perf-prefix-000171.yaml
- manifests/perf-prefix-000172.yaml
- manifests/perf-prefix-000173.yaml
- manifests/perf-prefix-000174.yaml
- manifests/perf-prefix-000175.yaml
- manifests/perf-prefix-000176.yaml
- manifests/perf-prefix-000177.yaml
- manifests/perf-prefix-000178.yaml
- manifests/perf-prefix-000179.yaml
- manifests/perf-prefix-000180.yaml
- manifests/perf-prefix-000181.yaml
- manifests/perf-prefix-000182.yaml
- manifests/perf-prefix-000183.yaml
- manifests/perf-prefix-000184.yaml
- manifests/perf-prefix-000185.yaml
- manifests/perf-prefix-000186.yaml
- manifests/perf-prefix-000187.yaml
- manifests/perf-prefix-000188.yaml
- manifests/perf-prefix-000189.yaml
- manifests/perf-prefix-000190.yaml
- manifests/perf-prefix-000191.yaml
- manifests/perf-prefix-000192.yaml
- manifests/perf-prefix-000193.yaml
- manifests/perf-prefix-000194.yaml
- manifests/perf-prefix-000195.yaml
- manifests/perf-prefix-000196.yaml
- manifests/perf-prefix-000197.yaml
- manifests/perf-prefix-000198.yaml
- manifests/perf-prefix-000199.yaml
- manifests/perf-prefix-000200.yaml
- manifests/perf-prefix-000201.yaml
- manifests/perf-prefix-000202.yaml
- manifests/perf-prefix-000203.yaml
- manifests/perf-prefix-000204.yaml
- manifests/perf-prefix-000205.yaml
- manifests/perf-prefix-000206.yaml
- manifests/perf-prefix-000207.yaml
- manifests/perf-prefix-000208.yaml
- manifests/perf-prefix-000209.yaml
- manifests/perf-prefix-000210.yaml
- manifests/perf-prefix-000211.yaml
- manifests/perf-prefix-000212.yaml
- manifests/perf-prefix-000213.yaml
- manifests/perf-prefix-000214.yaml
- manifests/perf-prefix-000215.yaml
- manifests/perf-prefix-000216.yaml
- manifests/perf-prefix-000217.yaml
- manifests/perf-prefix-000218.yaml
- manifests/perf-prefix-000219.yaml
- manifests/perf-prefix-000220.yaml
- manifests/perf-prefix-000221.yaml
- manifests/perf-prefix-000222.yaml
- manifests/perf-prefix-000223.yaml
- manifests/perf-prefix-000224.yaml
- manifests/perf-prefix-000225.yaml
- manifests/perf-prefix-000226.yaml
- manifests/perf-prefix-000227.yaml
- manifests/perf-prefix-000228.yaml
- manifests/perf-prefix-000229.yaml
- manifests/perf-prefix-000230.yaml
- manifests/perf-prefix-000231.yaml
- manifests/perf-prefix-000232.yaml
- manifests/perf-prefix-000233.yaml
- manifests/perf-prefix-000234.yaml
- manifests/perf-prefix-000235.yaml
- manifests/perf-prefix-000236.yaml
- manifests/perf-prefix-000237.yaml
- manifests/perf-prefix-000238.yaml
- manifests/perf-prefix-000239.yaml
- manifests/perf-prefix-000240.yaml
- manifests/perf-prefix-000241.yaml
- manifests/perf-prefix-000242.yaml
- manifests/perf-prefix-000243.yaml
- manifests/perf-prefix-000244.yaml
- manifests/perf-prefix-000245.yaml
- manifests/perf-prefix-000246.yaml
- manifests/perf-prefix-000247.yaml
- manifests/perf-prefix-000248.yaml
- manifests/perf-prefix-000249.yaml
- manifests/perf-prefix-000250.yaml
- manifests/perf-prefix-000251.yaml
- manifests/perf-prefix-000252.yaml
- manifests/perf-prefix-000253.yaml
- manifests/perf-prefix-000254.yaml
- manifests/perf-prefix-000255.yaml
- manifests/perf-prefix-000256.yaml
- manifests/perf-prefix-000257.yaml
- manifests/perf-prefix-000258.yaml
- manifests/perf-prefix-000259.yaml
- manifests/perf-prefix-000260.yaml
- manifests/perf-prefix-000261.yaml
- manifests/perf-prefix-000262.yaml
- manifests/perf-prefix-000263.yaml
- manifests/perf-prefix-000264.yaml
- manifests/perf-prefix-000265.yaml
- manifests/perf-prefix-000266.yaml
- manifests/perf-prefix-000267.yaml
- manifests/perf-prefix-000268.yaml
- manifests/perf-prefix-000269.yaml
- manifests/perf-prefix-000270.yaml
- manifests/perf-prefix-000271.yaml
- manifests/perf-prefix-000272.yaml
- manifests/perf-prefix-000273.yaml
- manifests/perf-prefix-000274.yaml
- manifests/perf-prefix-000275.yaml
- manifests/perf-prefix-000276.yaml
- manifests/perf-prefix-000277.yaml
- manifests/perf-prefix-000278.yaml
- manifests/perf-prefix-000279.yaml
- manifests/perf-prefix-000280.yaml
- manifests/perf-prefix-000281.yaml
- manifests/perf-prefix-000282.yaml
- manifests/perf-prefix-000283.yaml
- manifests/perf-prefix-000284.yaml
- manifests/perf-prefix-000285.yaml
- manifests/perf-prefix-000286.yaml
- manifests/perf-prefix-000287.yaml
- manifests/perf-prefix-000288.yaml
- manifests/perf-prefix-000289.yaml
- manifests/perf-prefix-000290.yaml
- manifests/perf-prefix-000291.yaml
- manifests/perf-prefix-000292.yaml
- manifests/perf-prefix-000293.yaml
- manifests/perf-prefix-000294.yaml
- manifests/perf-prefix-000295.yaml
- manifests/perf-prefix-000296.yaml
- manifests/perf-prefix-000297.yaml
- manifests/perf-prefix-000298.yaml
- manifests/perf-prefix-000299.yaml
